/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as XboxClubRouteImport } from './routes/xbox-club'
import { Route as WizzgenRouteImport } from './routes/wizzgen'
import { Route as TwitchRouteImport } from './routes/twitch'
import { Route as IndexRouteImport } from './routes/index'

const XboxClubRoute = XboxClubRouteImport.update({
  id: '/xbox-club',
  path: '/xbox-club',
  getParentRoute: () => rootRouteImport,
} as any)
const WizzgenRoute = WizzgenRouteImport.update({
  id: '/wizzgen',
  path: '/wizzgen',
  getParentRoute: () => rootRouteImport,
} as any)
const TwitchRoute = TwitchRouteImport.update({
  id: '/twitch',
  path: '/twitch',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/twitch': typeof TwitchRoute
  '/wizzgen': typeof WizzgenRoute
  '/xbox-club': typeof XboxClubRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/twitch': typeof TwitchRoute
  '/wizzgen': typeof WizzgenRoute
  '/xbox-club': typeof XboxClubRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/twitch': typeof TwitchRoute
  '/wizzgen': typeof WizzgenRoute
  '/xbox-club': typeof XboxClubRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/twitch' | '/wizzgen' | '/xbox-club'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/twitch' | '/wizzgen' | '/xbox-club'
  id: '__root__' | '/' | '/twitch' | '/wizzgen' | '/xbox-club'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TwitchRoute: typeof TwitchRoute
  WizzgenRoute: typeof WizzgenRoute
  XboxClubRoute: typeof XboxClubRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/xbox-club': {
      id: '/xbox-club'
      path: '/xbox-club'
      fullPath: '/xbox-club'
      preLoaderRoute: typeof XboxClubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wizzgen': {
      id: '/wizzgen'
      path: '/wizzgen'
      fullPath: '/wizzgen'
      preLoaderRoute: typeof WizzgenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/twitch': {
      id: '/twitch'
      path: '/twitch'
      fullPath: '/twitch'
      preLoaderRoute: typeof TwitchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TwitchRoute: TwitchRoute,
  WizzgenRoute: WizzgenRoute,
  XboxClubRoute: XboxClubRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
